<a href="https://colab.research.google.com/github/Farheena-NRIDegree/Python-mini-project-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy _ numeric python
#Most powerfull package _ library
#Numpy _ Dimensions
#A _ one Dimensional Array
#[A,B] || [A,
         #  B] _ Two Dimensional Array _ Row || column
# Three Dimensional
#Array _ storing manipulating, similar Data type
#Faster than any mathematical functions
# Convincent compared to other packages
# memory efficiency
# support multi dimensional arrays
# speed(numpy operations) > speed (lists operations)
# size (numpy opretions) > size (lists operations)
# memory(numpy)

In [ ]:
import numpy as np

In [ ]:
# create a numpy array
# 1D array

arr1D = np.array([1,2,3,4,5])
print(arr1D)

[1 2 3 4 5]


In [ ]:
 # create 2D array _ matrix
 arr2D = np.array([
     [1,2,3],[4,5,6]
  ])
 print(arr2D)

[[1 2 3]
 [4 5 6]]


In [ ]:
#creating arrays with default values
allzeros = np.zeros([2,3])
print(allzeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#creating matrix with values of elements as '1'
allones = np.ones([2,3])
print(allones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#creating matrix with values of elements as 'constant value _ n ~ fill value'
allconstant = np.full([2,3],6)
print(allconstant)

[[6 6 6]
 [6 6 6]]


In [ ]:
#create an identity matrix _ I
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Identity matrix _ Anii = 1 && Aij = 0
#for all A Belongs to R MxN
#Aij

In [ ]:
# creating random matrices
#With 0 and 1
rand1 = np.random.rand(3,3)
print(rand1)

# between a and b
rand2 = np.random.randint(10, 20,size=(3,3))
print(rand2)

[[0.45370695 0.47418074 0.34942434]
 [0.49373574 0.83019359 0.5825679 ]
 [0.31744456 0.2294497  0.95021412]]
[[19 18 16]
 [18 10 14]
 [11 16 18]]


In [ ]:
# Array Properties
arr = np.array([[1,2,3,4],[1,4,5,6]])
print(arr)

# Shape of array
print(f'\nThe shape of the array is {arr.shape}')

# Size of array
print(f'The size of the array is {arr.size}')

# Datatype of array
print(f'The Data type of the array is {arr.dtype}')

# Dimensions of array
print(f'The Dimension of the array is {arr.ndim}')

[[1 2 3 4]
 [1 4 5 6]]

The shape of the array is (2, 4)
The size of the array is 8
The Data type of the array is int64
The Dimension of the array is 2


In [ ]:
# indexing and slicing

#Access the elements in 1D Array

arr = np.array([1,2,3,4])
print(arr)
print(arr[3])

[1 2 3 4]
4


In [ ]:
# slicing the elements

print(arr[0:3])

# Access the element in 2D Array

arr2 = np.array([[1,2,3],[2,3,4]])

print(arr2)

print(arr2[1,1])

print(arr2[0,:])# First row with all columns

print(arr2[:,0])# First column with all rows

[1 2 3]
[[1 2 3]
 [2 3 4]]
3
[1 2 3]
[1 2]


In [ ]:
!pip install numpy

In [ ]:
#l1 = []
#[l1.append(_) for _in range(10)]
L1 = np.arange(10,-10,-3)
print(L1)

[10  7  4  1 -2 -5 -8]


In [ ]:
#Mathematical operations
a = np.array([1,2,3])
b = np.array([3,4,5])
print(f'The sum of a and b is { a + b}')
print(f'The sum of a and b is { a * b}')
print(f'The sum of a and b is { a / b}')

The sum of a and b is [4 6 8]
The sum of a and b is [ 3  8 15]
The sum of a and b is [0.33333333 0.5        0.6       ]


In [ ]:
#Matrix multiplication
b1 = np.array([[1,2,3,],[2,3,4,]])
b2 = np.array([[5,6,],[7,8],[1,3]])

#Dot product --- product = AB -- A MxN -- Bnxp
c = np.dot(b1,b2)
print(c)

[[22 31]
 [35 48]]


In [ ]:
print(b1)

[[1 2 3]
 [2 3 4]]


In [ ]:
print(b2)

[[5 6]
 [7 8]
 [1 3]]


In [ ]:
[
   [22, 31],
   [35, 48],
]

[[22, 31], [35, 48]]