<a href="https://colab.research.google.com/github/Farheena-NRIDegree/Python-mini-project-/blob/main/Numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 import numpy as np

In [ ]:
#Recap
arr = np.array([[1,2,3],[4,5,6]])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
#dot product _ m x n || n x p
arr1 = np.random.randint (1,2,(3,1))

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr1.shape

(3, 1)

In [ ]:
result = np.dot(arr, arr1)

In [ ]:
print(result)

[[ 6]
 [15]]


In [ ]:
r1 = np.random.randint(10,20,(3,3))
print(r1)

[[18 14 10]
 [15 17 15]
 [10 12 10]]


In [ ]:
r2 =np.eye(3)
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
r1_inv = np.linalg.inv(r1)
result2 = np.dot(r2, r1)
print(result2)

[[18. 14. 10.]
 [15. 17. 15.]
 [10. 12. 10.]]


In [ ]:
#M . I = I . M = M

In [ ]:
#A . B != B . A

In [ ]:
# mathematical operations

In [ ]:
# + _ * /

In [ ]:
t1 = np.random.randint(3,6,(3,3))
t2 = np.random.randint(3,6,(3,3))

In [ ]:
print(t1)

[[5 3 4]
 [3 3 4]
 [4 4 4]]


In [ ]:
print(t2)

[[4 5 3]
 [5 5 5]
 [5 5 3]]


In [ ]:
t3 = t1 + t2
print(t3)

[[9 8 7]
 [8 8 9]
 [9 9 7]]


In [ ]:
# matrix multiplication
result = np.dot(arr,arr1)

In [ ]:
# statistical operations

In [ ]:
mean = t3.mean()
mode = t3.max()
median = np.median(t3)
std = np.std(t3)
Var = np.var(t3)

In [ ]:
print(mean)
print(mode)
print(median)
print(std)
print(Var)

8.222222222222221
9
8.0
0.7856742013183861
0.6172839506172838


In [ ]:
print(std)

0.7856742013183861


In [ ]:
std*std

0.6172839506172838

In [ ]:
# Trigonometric functions

In [ ]:
# sin(x)
# cos(x)
# tan(x) _ sin(x)\ cos(x)
# cosec _ 1\sin(x)
# sen _ 1\ cos(x)
# cot _ 1 \ tan(x)

#
angles = np.array([0,15,30,45,60,75,90])
# sin(array)
result = np.sin(np.radians(angles))
result1= np.cos(np.radians(angles))
result2= np.tan(np.radians(angles))

In [ ]:
print(result)
print(result1)
print(result2)

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[[18. 14. 10.]
 [15. 17. 15.]
 [10. 12. 10.]]


In [ ]:
arr = np.array([1,2,3,4,5,6])

# Reshape the array
reshapedarr = arr.reshape(3,2)

print(reshapedarr)

# Convert / Flatten any n dim array
flattenedarr = arr.flatten()

print(flattenedarr)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [ ]:
#Stacking the data
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])
arr3 = np.vstack((arr1,arr2))
print(f" The shape of arr3 is {arr3.shape}")

# Horizontal stacking
arr4 = np.hstack((arr1,arr2))
print(f"The shape of arr4 is {arr4.shape}")
print(arr4)

 The shape of arr3 is (2, 4)
The shape of arr4 is (8,)
[ 1  2  3  4 10 20 30 40]


In [ ]:
#Filtering
arr = np.array([10,20,30,40,50,60,70,80])
farr = arr[arr > 40]

print(farr)

[50 60 70 80]
